Repository librespot-org/librespot, pull requests merged in 2020-07, with the labels that each got.

#476 Fix utf username
  connect/src/spirc.rs
  core/src/mercury/mod.rs
  core/src/util/mod.rs
Labels: bug

#456 Add gstreamer backend to librespot
  .travis.yml
  Cargo.lock
  Cargo.toml
  playback/Cargo.toml
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/mod.rs
  playback/src/lib.rs
Labels: audio

#447 Refactor Volume control, allow for a fixed volume option
  connect/src/spirc.rs
  core/src/config.rs
  src/main.rs
Labels: audio, enhancement

#443 [alsa] Implement cubic mapping for hardware mixers
  playback/src/mixer/alsamixer.rs
  playback/src/mixer/mod.rs
  src/main.rs
Labels: audio, enhancement
