Repository librespot-org/librespot, pull requests merged in 2021-11, with the labels that each got.

#875 Refactor main.rs
  CHANGELOG.md
  core/src/config.rs
  playback/src/audio_backend/mod.rs
  playback/src/config.rs
  playback/src/mixer/mod.rs
  src/main.rs
Labels: enhancement, breaking

#880 Guard against tracks_len being zero
  connect/src/spirc.rs
Labels: bug, SpotifyAPI

#883 Improve `--device ?` functionality for the alsa backend
  CHANGELOG.md
  playback/src/audio_backend/alsa.rs
Labels: enhancement, audio

#888 Harden systemd service, update restart policy
  CHANGELOG.md
  contrib/librespot.service
  contrib/librespot.user.service
Labels: enhancement
