Repository librespot-org/librespot, pull requests merged in 2021-06, with the labels that each got.

#785 Revert `math::round_half_to_even`
  Cargo.lock
  playback/Cargo.toml
  playback/src/convert.rs
Labels: audio, bug

#783 Remove feature gate around `apresolve`
  Cargo.toml
  core/Cargo.toml
  core/src/apresolve.rs
  core/src/lib.rs
Labels: bug

#789 Improve ALSA buffer size
  CHANGELOG.md
  playback/src/audio_backend/alsa.rs
Labels: audio

#795 Resolve `dealer` and `spclient` access points
  Cargo.toml
  core/Cargo.toml
  core/src/apresolve.rs
  core/src/lib.rs
  core/src/session.rs
Labels: new api

#797 Better errors alsa backend
  CHANGELOG.md
  playback/Cargo.toml
  playback/src/audio_backend/alsa.rs
  playback/src/player.rs
Labels: audio

#803 Fix clippy warnings
  playback/src/audio_backend/alsa.rs
Labels: audio, compilation

#804 Make CI ignore things that should not trigger build tests
  .github/workflows/test.yml
Labels: compilation

#802 Better errors in pipe backend
  CHANGELOG.md
  playback/src/audio_backend/pipe.rs
Labels: audio

#807 Make CI ignore things that should not trigger build tests (reprise)
  .github/workflows/test.yml
Labels: compilation

#813 Don't explicitly set the number of periods
  playback/src/audio_backend/alsa.rs
Labels: A-Alsa, audio, bug

#763 Adjust arg types of `Credentials::with_blob`
  core/src/authentication.rs
  discovery/src/server.rs
Labels: refactoring

#814 make convert and decoder public as they are needed by Sink traits
  CHANGELOG.md
  playback/src/lib.rs
Labels: audio

#801 Better errors in PulseAudio backend
  CHANGELOG.md
  playback/Cargo.toml
  playback/src/audio_backend/pulseaudio.rs
Labels: audio

#817 Update crates
  Cargo.lock
Labels: dependencies
