Repository librespot-org/librespot, pull requests merged in 2021-12, with the labels that each got.

#886 parse environment variables
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#896 Dynamic failable buffer sizing alsa-backend
  playback/src/audio_backend/alsa.rs
Labels: audio

#905 Skip track on decoding error
  playback/src/player.rs
Labels: bug, audio

#907 Add arm64 target example
  contrib/Dockerfile
Labels: enhancement, wiki

#899 Fix Command line arguments incorrectly echoed in TRACE
  src/main.rs
Labels: bug

#910 Fix auto fallback for --alsa-mixer-device and --alsa-mixer-index
  CHANGELOG.md
  src/main.rs
Labels: bug, audio

#916 Remove that last couple unwraps from main
  src/main.rs
Labels: bug

#919 player: ensure load threads are done when dropping PlayerInternal
  Cargo.lock
  playback/Cargo.toml
  playback/src/player.rs
Labels: bug, new api
