Repository librespot-org/librespot, pull requests merged in 2021-09, with the labels that each got.

#841 Fix clippy warnings
  audio/src/decrypt.rs
  connect/src/spirc.rs
  core/src/connection/handshake.rs
  metadata/src/lib.rs
  playback/src/audio_backend/alsa.rs
Labels: refactoring

#840 Attenuate after normalisation
  playback/src/player.rs
Labels: audio

#842 Update default normalisation threshold
  CHANGELOG.md
  playback/src/config.rs
  src/main.rs
Labels: reverse engineering, audio

#846 metadata: avoid unwrapping when parsing a playlist
  CHANGELOG.md
  metadata/src/lib.rs
Labels: bug

#844 Add and default to "auto" normalisation type
  CHANGELOG.md
  audio/src/fetch/receive.rs
  connect/src/spirc.rs
  playback/src/config.rs
  playback/src/player.rs
  src/main.rs
Labels: enhancement, audio

#823 Improve player
  CHANGELOG.md
  playback/Cargo.toml
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/decoder/lewton_decoder.rs
  playback/src/decoder/mod.rs
  playback/src/decoder/passthrough_decoder.rs
  playback/src/lib.rs
  playback/src/player.rs
Labels: enhancement, audio

#849 Fix Rust beta compiler warnings
  Cargo.lock
Labels: compilation, dependencies

#852 Add more platforms to keyexchange.proto
  protocol/proto/keyexchange.proto
Labels: enhancement, new api

#851 Add Google sign in credential to protobufs
  protocol/proto/spotify/login5/v3/credentials/credentials.proto
  protocol/proto/spotify/login5/v3/login5.proto
Labels: enhancement, new api

#820 Implement common SinkError and SinkResult
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/mod.rs
  playback/src/audio_backend/pipe.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/audio_backend/subprocess.rs
Labels: enhancement, audio
