Repository librespot-org/librespot, pull requests merged in 2021-05, with the labels that each got.

#692 Move decoder to playback crate
  .github/workflows/test.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  audio/Cargo.toml
  audio/src/lib.rs
  playback/Cargo.toml
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/mod.rs
  playback/src/audio_backend/pipe.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/audio_backend/subprocess.rs
  playback/src/config.rs
  playback/src/convert.rs
  playback/src/decoder/lewton_decoder.rs
  playback/src/decoder/libvorbis_decoder.rs
  playback/src/decoder/mod.rs
  playback/src/decoder/passthrough_decoder.rs
  playback/src/lib.rs
  playback/src/player.rs
Labels: breaking

#758 Bump jack and Rodio crates
  Cargo.lock
  playback/Cargo.toml
Labels: audio, dependencies

#753 Add basic websocket support
  Cargo.lock
  core/Cargo.toml
  core/src/apresolve.rs
  core/src/connection/mod.rs
  core/src/dealer/maps.rs
  core/src/dealer/mod.rs
  core/src/dealer/protocol.rs
  core/src/lib.rs
  core/src/session.rs
  core/src/socket.rs
  core/src/util.rs
Labels: new api

#673 Create separate discovery crate
  .github/workflows/test.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  connect/Cargo.toml
  connect/src/discovery.rs
  connect/src/lib.rs
  core/src/config.rs
  discovery/Cargo.toml
  discovery/examples/discovery.rs
  discovery/src/lib.rs
  discovery/src/server.rs
  src/lib.rs
  src/main.rs
Labels: enhancement

#685 Optimize volume control logic
  CHANGELOG.md
  connect/src/spirc.rs
  core/src/config.rs
  playback/src/config.rs
  playback/src/mixer/alsamixer.rs
  playback/src/mixer/mappings.rs
  playback/src/mixer/mod.rs
  playback/src/mixer/softmixer.rs
  playback/src/player.rs
  src/main.rs
Labels: breaking

#694 Implement dithering
  CHANGELOG.md
  Cargo.lock
  playback/Cargo.toml
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/mod.rs
  playback/src/audio_backend/pipe.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/audio_backend/subprocess.rs
  playback/src/config.rs
  playback/src/convert.rs
  playback/src/decoder/libvorbis_decoder.rs
  playback/src/dither.rs
  playback/src/lib.rs
  playback/src/player.rs
  src/main.rs
Labels: breaking

#750 Remove `with-vorbis` and `with-tremor` features
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  playback/Cargo.toml
  playback/src/decoder/mod.rs
Labels: breaking, dependencies

#762 Mostly cosmetic changes in `dealer`
  core/src/dealer/mod.rs
  core/src/dealer/protocol.rs
Labels: new api

#775 Run `cargo update`
  Cargo.lock
Labels: dependencies

#771 Round half away from zero and clean up noise shaping leftovers
  Cargo.lock
  playback/Cargo.toml
  playback/src/convert.rs
  playback/src/dither.rs
Labels: audio

#773 Keep samples in 64 bit
  CHANGELOG.md
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/mod.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/config.rs
  playback/src/convert.rs
  playback/src/decoder/lewton_decoder.rs
  playback/src/decoder/mod.rs
  playback/src/dither.rs
  playback/src/mixer/alsamixer.rs
  playback/src/mixer/mappings.rs
  playback/src/mixer/mod.rs
  playback/src/mixer/softmixer.rs
  playback/src/player.rs
  src/main.rs
Labels: audio, enhancement

#778 Fix output on big-endian systems
  CHANGELOG.md
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/convert.rs
Labels: audio, bug

#777 Various code improvements
  CHANGELOG.md
  audio/src/fetch/mod.rs
  audio/src/fetch/receive.rs
  audio/src/lib.rs
  connect/src/spirc.rs
  core/src/channel.rs
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/mod.rs
  playback/src/audio_backend/pipe.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/audio_backend/subprocess.rs
  playback/src/config.rs
  playback/src/convert.rs
  playback/src/decoder/lewton_decoder.rs
  playback/src/decoder/passthrough_decoder.rs
  playback/src/dither.rs
  playback/src/lib.rs
  playback/src/mixer/alsamixer.rs
  playback/src/mixer/mod.rs
  playback/src/mixer/softmixer.rs
  playback/src/player.rs
  src/main.rs
Labels: breaking, refactoring
