Repository librespot-org/librespot, pull requests merged in 2021-02, with the labels that each got.

#582 Refactor Cache and remove Volume struct
  audio/src/fetch.rs
  connect/src/spirc.rs
  core/src/authentication.rs
  core/src/cache.rs
  core/src/lib.rs
  core/src/volume.rs
  src/main.rs
Labels: enhancement

#573 Add option to choose between track or album normalisation gain
  playback/src/config.rs
  playback/src/player.rs
  src/main.rs
Labels: breaking, enhancement

#526 Align PLAYER_EVENT naming
  src/player_event_handler.rs
Labels: breaking

#566 fix: map authentication errors to a custom error type
  core/src/authentication.rs
  core/src/connection/mod.rs
  core/src/session.rs
  src/main.rs
Labels: breaking, enhancement

#569 Allow pipeline writer to spit out Ogg directly, including when seeking
  .gitignore
  Cargo.lock
  audio/Cargo.toml
  audio/src/lewton_decoder.rs
  audio/src/lib.rs
  audio/src/libvorbis_decoder.rs
  audio/src/passthrough_decoder.rs
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/mod.rs
  playback/src/audio_backend/pipe.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/audio_backend/subprocess.rs
  playback/src/config.rs
  playback/src/player.rs
  src/main.rs
Labels: audio, enhancement

#595 Replace version functions by constants
  connect/src/spirc.rs
  core/build.rs
  core/src/config.rs
  core/src/connection/mod.rs
  core/src/version.rs
  src/main.rs
Labels: breaking
