Repository librespot-org/librespot, pull requests merged in 2022-01, with the labels that each got.

#920 Sink: pass ownership of the packet on write()
  CHANGELOG.md
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/mod.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/player.rs
Labels: enhancement, audio

#922 Clean up list_compatible_devices
  playback/src/audio_backend/alsa.rs
Labels: enhancement, audio

#926 Fix clippy lint warning
  playback/src/audio_backend/portaudio.rs
Labels: enhancement, audio, compilation

#925 Handle reset and decode errors with the Symphonia decoder.
  playback/src/decoder/symphonia_decoder.rs
Labels: enhancement, audio, new api

#938 Fix `--device` argument to various backends
  CHANGELOG.md
  playback/src/audio_backend/pipe.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/subprocess.rs
  src/main.rs
Labels: bug, audio

#935 New dynamic limiter for very wide dynamic ranges
  CHANGELOG.md
  playback/src/config.rs
  playback/src/player.rs
  src/main.rs
Labels: enhancement, audio

#940 Remove unsafe code
  CHANGELOG.md
  core/src/cache.rs
  core/src/spotify_id.rs
  metadata/src/lib.rs
  playback/src/player.rs
  src/player_event_handler.rs
Labels: enhancement, breaking

#944 Update connectivity.proto
  core/src/spclient.rs
  protocol/proto/connectivity.proto
Labels: enhancement, new api

#942 simplify get_factor
  CHANGELOG.md
  playback/src/player.rs
Labels: audio, refactoring

#950 Fix Alsa softvol linear mapping
  CHANGELOG.md
  playback/src/mixer/alsamixer.rs
Labels: bug, audio, A-Alsa

#954 Remove basic normalisation deprecation warning
  src/main.rs
Labels: audio
