Repository librespot-org/librespot, pull requests merged in 2022-05, with the labels that each got.

#986 Remove the volume sample iteration
  examples/play.rs
  playback/src/mixer/mod.rs
  playback/src/mixer/softmixer.rs
  playback/src/player.rs
  src/main.rs
Labels: audio, breaking

#998 Bump MSRV to 1.53
  .github/workflows/test.yml
  CHANGELOG.md
  COMPILING.md
Labels: compilation

#995 Allow to override build_id with SOURCE_DATE_EPOCH
  core/build.rs
Labels: enhancement, compilation

#983 adding callback for reusable credentials
  CHANGELOG.md
  core/src/session.rs
  core/tests/connect.rs
  examples/get_token.rs
  examples/play.rs
  examples/playlist_tracks.rs
  src/main.rs
Labels: enhancement

#979 Backport sdroege's gstreamer backend cleanup to dev.
  CHANGELOG.md
  Cargo.lock
  playback/Cargo.toml
  playback/src/audio_backend/gstreamer.rs
Labels: enhancement, audio

#1002 Fix CI on ARM
  .github/workflows/test.yml
Labels: bug, compilation

#1003 Fix clippy lints
  core/build.rs
  discovery/Cargo.toml
  discovery/src/lib.rs
  playback/src/mixer/alsamixer.rs
  playback/src/mixer/mappings.rs
  playback/src/mixer/softmixer.rs
  src/main.rs
Labels: compilation

#1004 Update crates
  Cargo.lock
  playback/Cargo.toml
Labels: dependencies

#1007 Update deps round 2
  .github/workflows/test.yml
  CHANGELOG.md
  COMPILING.md
  Cargo.lock
  playback/Cargo.toml
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/sdl.rs
Labels: dependencies
