Repository librespot-org/librespot, pull requests merged in 2022-08, with the labels that each got.

#1032 Fix #1031 - Remove `new-api` branch from test matrix
  .github/workflows/test.yml
Labels: compilation

#1034 Add minimum rust version
  COMPILING.md
  Cargo.toml
  audio/Cargo.toml
  connect/Cargo.toml
  core/Cargo.toml
  discovery/Cargo.toml
  metadata/Cargo.toml
  playback/Cargo.toml
  protocol/Cargo.toml
Labels: enhancement, compilation

#1018 include more metadata in track struct
  metadata/src/artist.rs
  metadata/src/track.rs
Labels: enhancement, new api

#1036 Implement additional metadata for Artist
  metadata/src/artist.rs
Labels: enhancement, new api

#1037 Implement `DerefMut` for wrapper types in metadata
  metadata/src/album.rs
  metadata/src/artist.rs
  metadata/src/audio/file.rs
  metadata/src/availability.rs
  metadata/src/content_rating.rs
  metadata/src/copyright.rs
  metadata/src/episode.rs
  metadata/src/external_id.rs
  metadata/src/image.rs
  metadata/src/playlist/attribute.rs
  metadata/src/playlist/item.rs
  metadata/src/playlist/list.rs
  metadata/src/playlist/operation.rs
  metadata/src/playlist/permission.rs
  metadata/src/restriction.rs
  metadata/src/sale_period.rs
  metadata/src/track.rs
  metadata/src/util.rs
  metadata/src/video.rs
Labels: enhancement, new api

#1038 Fix panic in `ApResolver::resolve`
  core/src/apresolve.rs
  src/main.rs
Labels: bug, new api

#1040 Return iterators instead of collected vecs
  examples/playlist_tracks.rs
  metadata/src/album.rs
  metadata/src/artist.rs
  metadata/src/playlist/list.rs
Labels: enhancement, new api

#1039 Migrate to Rust 2021
  Cargo.toml
  audio/Cargo.toml
  audio/src/range_set.rs
  connect/Cargo.toml
  connect/src/spirc.rs
  core/Cargo.toml
  core/src/config.rs
  core/src/file_id.rs
  core/src/lib.rs
  core/src/spotify_id.rs
  discovery/Cargo.toml
  metadata/Cargo.toml
  metadata/src/restriction.rs
  playback/Cargo.toml
  playback/src/audio_backend/mod.rs
  playback/src/player.rs
  protocol/Cargo.toml
  protocol/src/lib.rs
  rustfmt.toml
Labels: compilation

#1041 Fix `SpClient::get_playlist` endpoint generation
  core/src/spclient.rs
Labels: bug, new api

#1042 Keep using the same hyper client
  core/src/http_client.rs
Labels: enhancement, new api
