Repository librespot-org/librespot, pull requests merged in 2022-02, with the labels that each got.

#962 Upgrade to Symphonia v0.5.
  Cargo.lock
  playback/Cargo.toml
  playback/src/decoder/symphonia_decoder.rs
  playback/src/player.rs
Labels: enhancement, audio, new api

#960 Prevent shuffle crash
  CHANGELOG.md
  connect/src/spirc.rs
Labels: bug

#966 Only log runtime argument if it starts with a dash "-"
  src/main.rs
Labels: bug

#964 Update to GStreamer bindings version 0.18 and various cleanups to the GStreamer audio backend
  .github/workflows/test.yml
  COMPILING.md
  Cargo.lock
  playback/Cargo.toml
  playback/src/audio_backend/gstreamer.rs
Labels: enhancement, audio, dependencies

#965 Quantum Realm level normalisation optimization
  playback/src/convert.rs
  playback/src/dither.rs
  playback/src/player.rs
Labels: audio, refactoring
