Repository librespot-org/librespot, pull requests merged in 2023-01, with the labels that each got.

#1084 [dev] core: spclient: parse lyrics
  CHANGELOG.md
  Cargo.lock
  connect/src/spirc.rs
  core/src/authentication.rs
  discovery/src/server.rs
  metadata/Cargo.toml
  metadata/src/audio/item.rs
  metadata/src/lib.rs
  metadata/src/lyrics.rs
  playback/src/convert.rs
  playback/src/lib.rs
  playback/src/player.rs
  protocol/build.rs
Labels: enhancement, new api

#1088 Parse playlist URIs with named IDs
  CHANGELOG.md
  core/src/spotify_id.rs
Labels: bug

#1089 Handle microsecond timestamps
  CHANGELOG.md
  metadata/src/playlist/list.rs
Labels: bug

#1090 Update sysinfo, fixing a future incompatibility warning
  Cargo.lock
  core/Cargo.toml
Labels: dependencies

#1092 Update protobuf and related crates to 3.x
  Cargo.lock
  connect/Cargo.toml
  connect/src/spirc.rs
  core/Cargo.toml
  core/src/authentication.rs
  core/src/cdn_url.rs
  core/src/connection/handshake.rs
  core/src/connection/mod.rs
  core/src/date.rs
  core/src/error.rs
  core/src/file_id.rs
  core/src/mercury/mod.rs
  core/src/spclient.rs
  core/src/spotify_id.rs
  metadata/Cargo.toml
  metadata/src/album.rs
  metadata/src/artist.rs
  metadata/src/audio/file.rs
  metadata/src/availability.rs
  metadata/src/content_rating.rs
  metadata/src/copyright.rs
  metadata/src/episode.rs
  metadata/src/external_id.rs
  metadata/src/image.rs
  metadata/src/lib.rs
  metadata/src/playlist/annotation.rs
  metadata/src/playlist/attribute.rs
  metadata/src/playlist/diff.rs
  metadata/src/playlist/item.rs
  metadata/src/playlist/list.rs
  metadata/src/playlist/operation.rs
  metadata/src/playlist/permission.rs
  metadata/src/restriction.rs
  metadata/src/sale_period.rs
  metadata/src/show.rs
  metadata/src/track.rs
  protocol/Cargo.toml
  protocol/build.rs
Labels: dependencies

#1113 Fix newly reported clippy errors
  audio/src/fetch/receive.rs
  audio/src/range_set.rs
  core/build.rs
  core/src/apresolve.rs
  core/src/cache.rs
  core/src/mercury/mod.rs
  core/src/proxytunnel.rs
  core/src/spclient.rs
  metadata/src/request.rs
  playback/src/audio_backend/alsa.rs
  playback/src/audio_backend/gstreamer.rs
  playback/src/audio_backend/jackaudio.rs
  playback/src/audio_backend/portaudio.rs
  playback/src/audio_backend/pulseaudio.rs
  playback/src/audio_backend/rodio.rs
  playback/src/audio_backend/sdl.rs
  playback/src/decoder/passthrough_decoder.rs
  playback/src/decoder/symphonia_decoder.rs
  src/main.rs
Labels: refactoring
