Repository librespot-org/librespot, pull requests merged in 2023-06, with the labels that each got.

#1165 Read Normalisation Data in one go
  playback/src/player.rs
Labels: enhancement, audio

#1150 Check formatting and linting first on workflow
  .github/workflows/test.yml
Labels: compilation

#1181 Update quick-xml to 0.29
  Cargo.lock
  core/Cargo.toml
Labels: dependencies
