Repository librespot-org/librespot, pull requests merged in 2025-08, with the labels that each got.

#1524 fix: add fallback logic for CDN urls
  CHANGELOG.md
  audio/src/fetch/mod.rs
  core/src/cdn_url.rs
  core/src/spclient.rs
Labels: enhancement, new api

#1485 Normalizer stereo imaging and performance improvements
  CHANGELOG.md
  playback/src/player.rs
Labels: enhancement, audio

#1541 feat: native TLS
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.alpine
  .devcontainer/devcontainer.json
  .github/workflows/build.yml
  .github/workflows/cross-compile.yml
  .github/workflows/quality.yml
  .github/workflows/test.yml
  CHANGELOG.md
  COMPILING.md
  Cargo.lock
  Cargo.toml
  Cross.toml
  README.md
  audio/Cargo.toml
  audio/src/fetch/mod.rs
  connect/Cargo.toml
  core/Cargo.toml
  core/src/http_client.rs
  discovery/Cargo.toml
  discovery/examples/discovery.rs
  discovery/examples/discovery_group.rs
  metadata/Cargo.toml
  metadata/src/lib.rs
  metadata/src/request.rs
  oauth/Cargo.toml
  oauth/examples/oauth_async.rs
  oauth/examples/oauth_sync.rs
  oauth/src/lib.rs
  playback/Cargo.toml
  playback/src/mixer/mappings.rs
  protocol/Cargo.toml
Labels: dependencies, refactoring

#1542 fix: rustls-tls features to support certificate stores
  .github/workflows/build.yml
  .github/workflows/cross-compile.yml
  .github/workflows/quality.yml
  COMPILING.md
  Cargo.lock
  Cargo.toml
  audio/Cargo.toml
  connect/Cargo.toml
  core/Cargo.toml
  core/src/http_client.rs
  discovery/Cargo.toml
  metadata/Cargo.toml
  oauth/Cargo.toml
  oauth/src/lib.rs
  playback/Cargo.toml
Labels: bug
